name: LID_PD
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - pip
  - python=3.9.18
  - readline
  - setuptools
  - tk
  - wheel
  - cudatoolkit
  - cudnn
  - edfio  # Aggiunto il pacchetto edfio tramite conda-forge
  - pip:
      - numpy
      - scipy
      - matplotlib
      - mne
      #- EntropyHub # Aggiunto il pacchetto EntropyHub
      - argparse
      - mne_icalabel
      - pyyaml
      - psutil
      - scikit-learn
      - seaborn
      - defusedxml
      - antropy
      - networkx
      - dyconnmap
      - mne_connectivity
      - protobuf==3.20
      - onnxruntime
      - missingno
      - pandas